### PR TITLE
Update to code for null-safety.

### LINKED ISSUE #2: null-safety?
Hi! Do you have any plans to create a null-safety release? I can help with this if you need any help although I don't really know how to properly create a tests for this.

### PR DESCRIPTION
**Pull request by asartalo**
- updated dependencies to use null-safe versions
- updated code to use null-safe features

Fixes #2

### CODE REVIEW

**Comment by asartalo** [comment]
I've tried to limit the changes to what is only needed to support null-safety. I've only tested this on a local project and it seems to work.

One issue that I found while using the null-safe version is that the hooks will refuse to execute if some of the dependencies in the hooks themselves are not null-safe. This will undoubtedly break projects that haven't opted-in to null-safety.

**Comment by asartalo** [comment]
Hi @xuzhongpeng , do you need this PR to be in the develop branch and not master? Let me know if this is the case and other issues you see in my PR.

**Comment by xuzhongpeng** [comment]
> Hi @xuzhongpeng , do you need this PR to be in the develop branch and not master? Let me know if this is the case and other issues you see in my PR.

I have reviewed the codes you pushed. It's running perfectly.  But it is only fit SDK >=1.12.0-0 <3.0.0. I may push it in the future, but not now.

**Comment by asartalo** [comment]
Okay, no problem. It's up to you. :) Just want to let you know that any project that is marked as null-safe by pub.dev like [http](https://pub.dev/packages/http/versions/0.13.0) have to limit their sdk support that way. See [http's pubspec.yaml](https://github.com/dart-lang/http/blob/master/pubspec.yaml) as an example and the documentation on [how to migrate packages to null-safety](https://dart.dev/null-safety/migration-guide#migrating-by-hand). If you need help with this I will gladly help but it's still up to you.

**Comment by xuzhongpeng** [comment]
> Okay, no problem. It's up to you. :) Just want to let you know that any project that is marked as null-safe by pub.dev like [http](https://pub.dev/packages/http/versions/0.13.0) have to limit their sdk support that way. See [http's pubspec.yaml](https://github.com/dart-lang/http/blob/master/pubspec.yaml) as an example and the documentation on [how to migrate packages to null-safety](https://dart.dev/null-safety/migration-guide#migrating-by-hand). If you need help with this I will gladly help but it's still up to you.

I have pulled your PR to nullSafety channel. I also have created a version [0.1.3-nullsafety.0](https://pub.dev/packages/git_hooks/versions/0.1.3-nullsafety.0) to pub.dev. Thank you for your code contribution.

**Pull request closed without merging**
